import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import React, { useState } from 'react';
import Image from 'next/image';

export default function Home() {
  const [input, setInput] = useState<string>();
  const [items, setItems] = useState([]);

  const searchItem = (e) => {
    e.preventDefault();
    const query = input;
    const API_Request = `https://www.googleapis.com/customsearch/v1?key=AIzaSyCrZ3vlyw-wI84iyL5nEv3ccfsYQTd28VI&cx=1ddc7e60039f419f6&searchType=image&q=${query}&num=5&start=1`;

    const getItemsData = async (): Promise<any> => {
      const result = await fetch(API_Request, {
        method: 'GET',
      }).then((response) => response.json());
      return result;
    };

    const fetchItemsData = async (): Promise<void> => {
      console.log('test');
      const itemsData = await getItemsData();
      console.log(itemsData);
      setItems(itemsData.items);
    };
    fetchItemsData();
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const target = e.target;
    const name = target.name;
    const value = target.value;
    setInput(value);
  };

  const selectImage = (e) => {
    const target = e.target;
    const targetKey = target.attributes.getNamedItem('data-id').value;
    console.log(target);
    console.log(targetKey);
    setItems([items[targetKey]]);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <p>野菜を検索しよう</p>
        <form>
          <input type='text' onChange={handleInputChange} />
          <button onClick={searchItem}>検索</button>
        </form>
        <div className={styles['image-container']}>
          {items && items.length > 0 ? (
            items.map((item, i) => (
              <div
                className={styles['refrigerator-image']}
                key={i}
                onClick={selectImage}
                data-id={i}
              >
                <img src={item.image.thumbnailLink} />
              </div>
            ))
          ) : (
            <p>nothing</p>
          )}
        </div>
      </main>
    </div>
  );
}
